import base64
import json
import os
import re
import sys
import urllib.error
import urllib.request
from datetime import datetime, timezone

USER = "tonn5698-glitch"
TOKEN = os.environ.get("GH_PROJECTS_TOKEN") or os.environ.get("GITHUB_TOKEN")


def api(path, per_page=100):
    url = f"https://api.github.com{path}"
    if per_page:
        sep = "&" if "?" in url else "?"
        url += f"{sep}per_page={per_page}&page=1"
    req = urllib.request.Request(url, headers={
        "Accept": "application/vnd.github+json",
        "User-Agent": "about-me-updater",
        "Authorization": f"Bearer {TOKEN}",
    })
    with urllib.request.urlopen(req) as resp:
        return json.load(resp)


def load_text(url):
    req = urllib.request.Request(url, headers={"User-Agent": "about-me-updater"})
    with urllib.request.urlopen(req) as resp:
        return resp.read().decode("utf-8")


def fmt_time(iso):
    try:
        dt = datetime.fromisoformat(iso.replace("Z", "+00:00"))
    except ValueError:
        return "unknown"
    now = datetime.now(timezone.utc)
    delta = now - dt
    secs = int(delta.total_seconds())
    if secs < 0:
        return "just now"
    if secs < 60:
        return f"{secs} seconds ago"
    mins = secs // 60
    if mins < 60:
        return f"{mins} min ago"
    hours = mins // 60
    if hours < 24:
        return f"{hours} hour{'s' if hours != 1 else ''} ago"
    days = hours // 24
    return f"{days} day{'s' if days != 1 else ''} ago"


def repo_card(name, pushed, desc):
    desc_esc = (desc or "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    repo_url = f"https://github.com/{USER}/{name}"
    og_url = f"https://opengraph.githubassets.com/1/{USER}/{name}"
    has_bg = desc is not None and desc.strip() != ""
    bg_class = " has-bg" if has_bg else ""
    link = f"<a class=\"repo-link\" href=\"{repo_url}\" target=\"_blank\" rel=\"noopener\">read more →</a>"
    return (
        f"<div class=\"repo-card{bg_class}\""
        + (f" style=\"background-image:url('{og_url}')\"" if has_bg else "")
        + ">\n"
        "        <div class=\"repo-time mono\">" + fmt_time(pushed) + "</div>\n"
        "        <h3>" + name + "</h3>\n"
        "        <p>" + (desc_esc if has_bg else "No description.") + "</p>\n"
        "        " + link + "\n"
        "      </div>"
    )


def header():
    return (
        "<div class=\"working-head\">\n"
        "        <h3>Working Project</h3>\n"
        "        <span class=\"last-commit\">Last commit</span>\n"
        "      </div>"
    )


def main():
    if not TOKEN:
        print("No token available", file=sys.stderr)
        sys.exit(1)

    try:
        repos = api(f"/users/{USER}/repos", per_page=100)
    except urllib.error.HTTPError as e:
        print(f"API error: {e.code} {e.reason}", file=sys.stderr)
        print(e.read().decode() if hasattr(e, "read") else "", file=sys.stderr)
        sys.exit(1)

    repos = [r for r in repos if not r.get("fork")]
    repos.sort(key=lambda r: r.get("pushed_at") or "", reverse=True)

    cards = [repo_card(r["name"], r["pushed_at"], r.get("description")) for r in repos[:30]]
    inner = "\n      ".join(cards) if cards else "<div class=\"repo-card\"><h3>No public repos.</h3></div>"
    block = header() + "\n      <div class=\"repo-slider\">\n      " + inner + "\n      </div>"
    block = "<!-- repo-list generated by GitHub Action -->\n      " + block + "\n      <!-- /repo-list -->"

    path = "dev.html"
    with open(path, encoding="utf-8") as f:
        html = f.read()

    pattern = re.compile(
        r"(<!-- START: repo-list -->\n)(.*?)(\n\s*<!-- END: repo-list -->)",
        re.DOTALL,
    )
    if not pattern.search(html):
        print("Markers not found in dev.html", file=sys.stderr)
        sys.exit(1)

    new_html = pattern.sub(r"\1" + block + r"\3", html)

    with open(path, "w", encoding="utf-8") as f:
        f.write(new_html)

    print(f"Updated {len(repos)} repos in dev.html")


if __name__ == "__main__":
    main()
